name : Index Test and Push

env:
  IMAGE_NAME: ??

on:
  pull_request:
    branches:
      - main
    paths:
      - 'index/**'
      - '.github/workflows/index-*'
  push:
    branches:
      - main
    paths:
      - 'index/version.txt'
      - '.github/workflows/index-*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Dockerized Tests for S3
      timeout-minutes: 20
      shell: bash
      run: |
        cd index
        make test-indexing
  push:
    if: github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get tag for this build if it exists
      run: |
        echo "VERSION=$(cat index/version.txt)" >> $GITHUB_ENV
    - name: Build and Push unstable Docker Image from PR / Push to Master
      uses: whoan/docker-build-with-cache-action@v4
      with:
        context: index
        image_name: ${{ env.IMAGE_NAME }}
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
        image_tag: latest,${{ env.VERSION }}

    - name: Update Docker Hub Description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
        repository: ${{ env.IMAGE_NAME }}
        readme-filepath: ./index/readme.md
        short-description: Open Data Cube Indexing Image