name : Deafrica Tools Test and Push

env:
  IMAGE_NAME: ??

on:
  pull_request:
    branches:
      - master
    paths:
      - 'deafrica_automation_tools/**'
      - '.github/workflows/deafrica-tools-*'
  push:
    branches:
      - master
    paths:
      - 'deafrica_automation_tools/_version.py'
      - '.github/workflows/deafrica-tools-*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

  push:
    if: github.ref == 'refs/heads/master'
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get tag for this build if it exists
      run: |
        echo "VERSION=$(cat deafrica_automation_tools/_version.py)" >> $GITHUB_ENV
    - name: Build and Push unstable Docker Image from PR / Push to Master
      uses: whoan/docker-build-with-cache-action@v4
      with:
        context: deafrica_automation_tools
        image_name: ${{ env.IMAGE_NAME }}
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
        image_tag: latest,${{ env.VERSION }}

    - name: Update Docker Hub Description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
        repository: ${{ env.IMAGE_NAME }}
        readme-filepath: ./index/readme.md
        short-description: Open Data Cube Indexing Image